What is the total revenue generated by male vs. female customers?
SELECT Gender, SUM(Purchase_Amount_USD) AS Revenue
FROM Customer
GROUP BY Gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select Customer_ID, Purchase_Amount_USD
from customer 
where Discount_Applied = 'Yes' and Purchase_Amount_USD >= (select AVG(Purchase_Amount_USD) from customer)


Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
    Item_Purchased,
    ROUND(AVG(CAST(Review_Rating AS FLOAT)), 2) AS [Average Product Rating]
FROM Customer
GROUP BY Item_Purchased
ORDER BY [Average Product Rating] DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select Shipping_Type, 
ROUND(AVG(Purchase_Amount_USD),2)
from customer
where Shipping_Type in ('Standard','Express')
group by Shipping_Type;


Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(Customer_ID) AS Total_customers,
       ROUND(AVG(Purchase_Amount_USD),2) AS avg_spend,
       ROUND(SUM(Purchase_Amount_USD),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
    Item_Purchased,
    ROUND(100.0 * SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS Discount_rate
FROM Customer
GROUP BY Item_Purchased
ORDER BY Discount_rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with Customer_type as (
SELECT Customer_ID, Previous_Purchases,
CASE 
    WHEN Previous_Purchases = 1 THEN 'New'
    WHEN Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS Customer_segment
FROM Customer)

select Customer_segment,count(*) AS "Number of Customers" 
from Customer_type 
group by Customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH Item_counts AS (
    SELECT Category,
           Item_Purchased,
           COUNT(Customer_ID) AS Total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(Customer_Id) DESC) AS Item_rank
    FROM Customer
    GROUP BY category, Item_Purchased
)
SELECT Item_rank,Category, Item_Purchased, Total_orders
FROM item_counts
WHERE item_rank <=3;
 

 Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT Subscription_Status,
       COUNT(Customer_ID) AS repeat_buyers
FROM Customer
WHERE Previous_Purchases > 5
GROUP BY Subscription_Status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    Age,
    SUM(Purchase_Amount_USD) AS Total_revenue
FROM Customer
GROUP BY Age
ORDER BY Total_revenue desc;







